<?php $product = Mage::registry('current_product'); ?>
<meta property="fb:app_id" content="<?php echo Mage::getStoreConfig('facebooklb/general/appid'); ?>"/>
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>"/>
<meta property="og:type" content="product"/>
<?php if ($product): ?>
<meta property="og:title" content="<?php echo htmlspecialchars(trim($product->getName())); ?>"/>
<meta property="og:image" content="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->resize(200,200);?>"/>
<?php endif; ?>
