<?php if (Mage::getStoreConfig('facebooklb/general/enabled')) : ?>
    <?php if (Mage::getStoreConfig('facebooklb/productlike/enabled')) : ?>
        <?php $product = Mage::registry('current_product'); ?>
        <div id="fb-root" data-locale="<?php echo Mage::getStoreConfig('facebooklb/general/lang')?>"></div>
        <div
            class="fb-like"
            data-href="<?php echo $product->getProductUrl() ?>"
            data-layout="<?php echo Mage::getStoreConfig('facebooklb/productlike/layout') ?>"
            data-action="<?php echo Mage::getStoreConfig('facebooklb/productlike/verb'); ?>"
            <?php if (Mage::getStoreConfig('facebooklb/productlike/showfaces')):?>
            data-show-faces="true"
            <?php endif; ?>
            data-width="<?php echo Mage::getStoreConfig('facebooklb/productlike/width'); ?>"
            <?php if (Mage::getStoreConfig('facebooklb/productlike/send')):?>
            data-share="true"
            <?php endif; ?>"
            <?php if (Mage::getStoreConfig('facebooklb/productlike/color') != 'light'):?>
            data-colorscheme="dark"
            <?php endif; ?>"
            ></div>
    <?php endif; ?>
<?php endif; ?>
