<script type="text/javascript">
    window.fbAsyncInit = function() {
        FB.init({
          appId  : <?php echo Mage::getStoreConfig('facebooklb/general/appid'); ?>,
          cookie : true,
          status : true,
          oauth  : true,
          xfbml  : true
        });
    };

    (function(d){
        var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
        var locale = '<?php echo Mage::getStoreConfig('facebooklb/general/lang') ?>';
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/" + locale + "/all.js";
        d.getElementsByTagName('head')[0].appendChild(js);
      }(document));
</script>
