<meta property="fb:app_id" content="<?php echo Mage::getStoreConfig('facebooklb/general/appid'); ?>"/>
<meta property="og:locale" content="<?php echo Mage::getStoreConfig('facebooklb/general/lang');?>"/>
<?php $product = Mage::registry('current_product'); ?>
<?php if ($product):
    $w = Mage::getStoreConfig('facebooklb/productlike/image_width');
    $h = Mage::getStoreConfig('facebooklb/productlike/image_width');
    $keep_frame = Mage::getStoreConfig('facebooklb/productlike/image_keep_frame');
    $src = Mage::helper('catalog/image')->init($product, 'image')->keepFrame($keep_frame);
    if ($w && $h) {
        $src->resize($w, $h);
    }
?>
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>"/>
<meta property="og:type" content="product"/>
<meta property="og:title" content="<?php echo htmlspecialchars(trim($product->getName())); ?>"/>
<meta property="og:image" content="<?php echo $src;?>"/>
<?php endif; ?>
